#pragma kernel NodeRelaxation

struct Node
{
    uint possibleTiles;
    int entropy;
    uint tile;
    int x;
    int y;
};

StructuredBuffer<int2> directions;

StructuredBuffer<Node> gridCurrent;
RWStructuredBuffer<Node> gridNext;

StructuredBuffer<uint> compat;

RWStructuredBuffer<int> changeFlag;

int tilesCount;

int gridSizeX;
int gridSizeY;

float IsInRange(int x, int min, int max)
{
    return (x >= min) * (x <= max);
}

uint CompNeighTiles(uint dToN, int t )
{
    return compat[t * 4 + (dToN + 2) % 4];
}

[numthreads(1,1,1)]
void NodeRelaxation (uint3 groupID : SV_GROUPID)
{
    int x = groupID.x;
    int y = groupID.y;

    int index = x * gridSizeY + y;
    Node node = gridCurrent[index];
    
    
    if(node.tile != 0)
    {
        gridNext[index] = node;
        return;
    }

    uint possibleTiles = node.possibleTiles;

    for (int d = 0; d < 4; d++) 
    {
        int2 direction = directions[d];

        int neighbourX = x + direction.x;
        int neighbourY = y + direction.y;

        float hasNeighbour = IsInRange(neighbourX, 0, gridSizeX - 1) * IsInRange(neighbourY, 0, gridSizeY - 1);

        if(hasNeighbour < 0.5)
            continue;
        
        int neighbourIndex = neighbourX * gridSizeY + neighbourY;
        Node neighbour = gridCurrent[neighbourIndex];
        
        if(neighbour.entropy == 1)
        {
            int t = firstbitlow(neighbour.possibleTiles);
            uint connectingTiles = CompNeighTiles(d, t);

            possibleTiles &= connectingTiles;

            if(possibleTiles != node.possibleTiles)
                changeFlag[0] = 1;

            continue;
        }
        
        uint neighbourTiles = neighbour.possibleTiles;
        uint neighbourTilesDup = neighbourTiles;
        uint possibleConnTiles = 0;

        while(neighbourTilesDup != 0)
        {
            int t = firstbitlow(neighbourTilesDup);

            uint connectingTiles = CompNeighTiles(d, t);
            possibleConnTiles |= connectingTiles;

            neighbourTilesDup &= (neighbourTilesDup - 1);
        }

        possibleTiles &= possibleConnTiles;
    }

    if(possibleTiles != node.possibleTiles)
    {
        changeFlag[0] = 1;
        node.possibleTiles = possibleTiles;
        node.entropy = countbits(possibleTiles);
    }

    node.tile = 0;
    gridNext[index] = node;
}
